sudo: false
language: python
python: 3.5
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install tox
env:
  - TOXENV=py27-django-18
  - TOXENV=py27-django-19
  - TOXENV=py27-django-110
  - TOXENV=py27-django-111
  - TOXENV=py35-django-18
  - TOXENV=py35-django-19
  - TOXENV=py35-django-110
  - TOXENV=py35-django-111
  - TOXENV=py35-django-master
  - TOXENV=pypy-django-18
  - TOXENV=pypy-django-19
  - TOXENV=pypy-django-110
  - TOXENV=pypy-django-111
  - TOXENV=pypy-django-master
matrix:
  allow_failures:
    - env: TOXENV=py27-django-111
    - env: TOXENV=py35-django-111
    - env: TOXENV=pypy-django-111
    - env: TOXENV=py35-django-master
    - env: TOXENV=pypy-django-master
script:
- tox
deploy:
  provider: pypi
  user: jazzband
  distributions: "sdist bdist_wheel"
  password:
    secure: VD+63Tnv0VYNfFQv9f1KZ0k79HSX8veNk4dTy42Hriteci50z5uSQdZMnqqD83xQJa4VF6N7DHkxHnBVOWLCqGQZeYqR/5BuDFNUewcr6O14dk31HvxMsWDaN1KW0Qwtus8ZrztwGhZtZ/92ODA6luHI4mCTzqX0gcG0/aKd75s=
  on:
    tags: true
    repo: jazzband/django-constance
    condition: "$TOXENV = py27-django-18"
